services:
  app:
    image: ghcr.io/regina-ms/converter:latest
    container_name: my-nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Монтируем папку uploads с VM внутрь контейнера
      # Левая часть — путь на VM, правая — внутри контейнера
      - /home/deploy/app/uploads:/app/uploads
    environment:
      - NODE_ENV=production
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/deploy/app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/deploy/app/certbot/www:/var/www/certbot:ro
      - /home/deploy/app/certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/deploy/app/certbot/www:/var/www/certbot
      - /home/deploy/app/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"